version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: chrome-aws-lambda
    versions:
    - 5.5.0
    - 7.0.0
    - 7.0.0
    - 8.0.0
  - dependency-name: puppeteer-core
    versions:
    - 5.5.0
    - 7.0.1
    - 7.0.4
    - 8.0.0
  - dependency-name: sharp
    versions:
    - 0.27.1
    - 0.27.2
    - 0.28.0
